spring.application.name=springexposed


# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/exposed?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Vaddshah2626!!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Enable automatic schema creation
spring.exposed.generate-ddl=true

# Enable SQL logging
spring.exposed.show-sql=true